In [1]:
import pandas as pd

# Read in data. The last 15 lines are comments.
deaths_2003 = pd.read_csv(
    "/Users/caleboneel/Desktop/estimating-impact-of-opioids-2020-purlple-team/00_source/US_VitalStatistics/UnderlyingCauseofDeath2003.txt",
    sep="\t",
    skipfooter=15,
    engine="python",
)
# Drop the Notes column
deaths_2003 = deaths_2003.drop(columns=["Notes"])

In [2]:
deaths_2003

,County,County Code,Year,Year Code,Drug/Alcohol Induced Cause,Drug/Alcohol Induced Cause Code,Deaths
0,"Autauga County, AL",1001,2003.0,2003.0,All other non-drug and non-alcohol causes,O9,397.0
1,"Baldwin County, AL",1003,2003.0,2003.0,Drug poisonings (overdose) Unintentional (X40-...,D1,10.0
2,"Baldwin County, AL",1003,2003.0,2003.0,All other alcohol-induced causes,A9,14.0
3,"Baldwin County, AL",1003,2003.0,2003.0,All other non-drug and non-alcohol causes,O9,1479.0
4,"Barbour County, AL",1005,2003.0,2003.0,All other non-drug and non-alcohol causes,O9,287.0
...,...,...,...,...,...,...,...
4082,"Sweetwater County, WY",56037,2003.0,2003.0,All other non-drug and non-alcohol causes,O9,272.0
4083,"Teton County, WY",56039,2003.0,2003.0,All other non-drug and non-alcohol causes,O9,85.0
4084,"Uinta County, WY",56041,2003.0,2003.0,All other non-drug and non-alcohol causes,O9,111.0
4085,"Washakie County, WY",56043,2003.0,2003.0,All other non-drug and non-alcohol causes,O9,88.0
4086,"Weston County, WY",56045,2003.0,2003.0,All other non-drug and non-alcohol causes,O9,63.0

In [3]:
deaths_2003['County'].value_counts()

Multnomah County, OR      6
Middlesex County, MA      6
Los Angeles County, CA    6
Tarrant County, TX        6
Maricopa County, AZ       6
                         ..
Hillsdale County, MI      1
Karnes County, TX         1
Scott County, KS          1
Smith County, MS          1
Alger County, MI          1
Name: County, Length: 3107, dtype: int64

In [4]:
# Read in data. The last 15 lines are comments.
deaths_2004 = pd.read_csv(
    "/Users/caleboneel/Desktop/estimating-impact-of-opioids-2020-purlple-team/00_source/US_VitalStatistics/UnderlyingCauseofDeath2004.txt",
    sep="\t",
    skipfooter=15,
    engine="python",
)
# Drop the Notes column
deaths_2004 = deaths_2004.drop(columns=["Notes"])

deaths_2004

,County,County Code,Year,Year Code,Drug/Alcohol Induced Cause,Drug/Alcohol Induced Cause Code,Deaths
0,"Autauga County, AL",1001,2004.0,2004.0,All other non-drug and non-alcohol causes,O9,373.0
1,"Baldwin County, AL",1003,2004.0,2004.0,Drug poisonings (overdose) Unintentional (X40-...,D1,18.0
2,"Baldwin County, AL",1003,2004.0,2004.0,All other alcohol-induced causes,A9,10.0
3,"Baldwin County, AL",1003,2004.0,2004.0,All other non-drug and non-alcohol causes,O9,1518.0
4,"Barbour County, AL",1005,2004.0,2004.0,All other non-drug and non-alcohol causes,O9,274.0
...,...,...,...,...,...,...,...
4130,"Sweetwater County, WY",56037,2004.0,2004.0,All other non-drug and non-alcohol causes,O9,269.0
4131,"Teton County, WY",56039,2004.0,2004.0,All other non-drug and non-alcohol causes,O9,72.0
4132,"Uinta County, WY",56041,2004.0,2004.0,All other non-drug and non-alcohol causes,O9,109.0
4133,"Washakie County, WY",56043,2004.0,2004.0,All other non-drug and non-alcohol causes,O9,89.0
4134,"Weston County, WY",56045,2004.0,2004.0,All other non-drug and non-alcohol causes,O9,55.0

In [5]:
deaths_2005 = pd.read_csv(
    "/Users/caleboneel/Desktop/estimating-impact-of-opioids-2020-purlple-team/00_source/US_VitalStatistics/UnderlyingCauseofDeath2005.txt",
    sep="\t",
    skipfooter=15,
    engine="python",
)
# Drop the Notes column
deaths_2005 = deaths_2005.drop(columns=["Notes"])

deaths_2005

,County,County Code,Year,Year Code,Drug/Alcohol Induced Cause,Drug/Alcohol Induced Cause Code,Deaths
0,"Autauga County, AL",1001,2005.0,2005.0,All other non-drug and non-alcohol causes,O9,447.0
1,"Baldwin County, AL",1003,2005.0,2005.0,Drug poisonings (overdose) Unintentional (X40-...,D1,14.0
2,"Baldwin County, AL",1003,2005.0,2005.0,All other alcohol-induced causes,A9,19.0
3,"Baldwin County, AL",1003,2005.0,2005.0,All other non-drug and non-alcohol causes,O9,1534.0
4,"Barbour County, AL",1005,2005.0,2005.0,All other non-drug and non-alcohol causes,O9,326.0
...,...,...,...,...,...,...,...
4197,"Sweetwater County, WY",56037,2005.0,2005.0,All other non-drug and non-alcohol causes,O9,239.0
4198,"Teton County, WY",56039,2005.0,2005.0,All other non-drug and non-alcohol causes,O9,76.0
4199,"Uinta County, WY",56041,2005.0,2005.0,All other non-drug and non-alcohol causes,O9,124.0
4200,"Washakie County, WY",56043,2005.0,2005.0,All other non-drug and non-alcohol causes,O9,89.0
4201,"Weston County, WY",56045,2005.0,2005.0,All other non-drug and non-alcohol causes,O9,71.0

In [6]:
# Read in data. The last 15 lines are comments.
deaths_2006 = pd.read_csv(
    "/Users/caleboneel/Desktop/estimating-impact-of-opioids-2020-purlple-team/00_source/US_VitalStatistics/UnderlyingCauseofDeath2006.txt",
    sep="\t",
    skipfooter=15,
    engine="python",
)
# Drop the Notes column
deaths_2006 = deaths_2006.drop(columns=["Notes"])

deaths_2006

,County,County Code,Year,Year Code,Drug/Alcohol Induced Cause,Drug/Alcohol Induced Cause Code,Deaths
0,"Autauga County, AL",1001,2006.0,2006.0,All other non-drug and non-alcohol causes,O9,449.0
1,"Baldwin County, AL",1003,2006.0,2006.0,Drug poisonings (overdose) Unintentional (X40-...,D1,11.0
2,"Baldwin County, AL",1003,2006.0,2006.0,All other alcohol-induced causes,A9,15.0
3,"Baldwin County, AL",1003,2006.0,2006.0,All other non-drug and non-alcohol causes,O9,1613.0
4,"Barbour County, AL",1005,2006.0,2006.0,All other non-drug and non-alcohol causes,O9,284.0
...,...,...,...,...,...,...,...
4257,"Sweetwater County, WY",56037,2006.0,2006.0,All other non-drug and non-alcohol causes,O9,242.0
4258,"Teton County, WY",56039,2006.0,2006.0,All other non-drug and non-alcohol causes,O9,70.0
4259,"Uinta County, WY",56041,2006.0,2006.0,All other non-drug and non-alcohol causes,O9,127.0
4260,"Washakie County, WY",56043,2006.0,2006.0,All other non-drug and non-alcohol causes,O9,77.0
4261,"Weston County, WY",56045,2006.0,2006.0,All other non-drug and non-alcohol causes,O9,70.0

In [7]:
deaths_2007 = pd.read_csv(
    "/Users/caleboneel/Desktop/estimating-impact-of-opioids-2020-purlple-team/00_source/US_VitalStatistics/UnderlyingCauseofDeath2007.txt",
    sep="\t",
    skipfooter=15,
    engine="python",
)
# Drop the Notes column
deaths_2007 = deaths_2007.drop(columns=["Notes"])

deaths_2007

,County,County Code,Year,Year Code,Drug/Alcohol Induced Cause,Drug/Alcohol Induced Cause Code,Deaths
0,"Autauga County, AL",1001,2007.0,2007.0,All other non-drug and non-alcohol causes,O9,399.0
1,"Baldwin County, AL",1003,2007.0,2007.0,Drug poisonings (overdose) Unintentional (X40-...,D1,24.0
2,"Baldwin County, AL",1003,2007.0,2007.0,All other alcohol-induced causes,A9,20.0
3,"Baldwin County, AL",1003,2007.0,2007.0,All other non-drug and non-alcohol causes,O9,1633.0
4,"Barbour County, AL",1005,2007.0,2007.0,All other non-drug and non-alcohol causes,O9,248.0
...,...,...,...,...,...,...,...
4299,"Sweetwater County, WY",56037,2007.0,2007.0,All other non-drug and non-alcohol causes,O9,264.0
4300,"Teton County, WY",56039,2007.0,2007.0,All other non-drug and non-alcohol causes,O9,63.0
4301,"Uinta County, WY",56041,2007.0,2007.0,All other non-drug and non-alcohol causes,O9,132.0
4302,"Washakie County, WY",56043,2007.0,2007.0,All other non-drug and non-alcohol causes,O9,82.0
4303,"Weston County, WY",56045,2007.0,2007.0,All other non-drug and non-alcohol causes,O9,79.0

In [8]:
# Read in data. The last 15 lines are comments.
deaths_2008 = pd.read_csv(
    "/Users/caleboneel/Desktop/estimating-impact-of-opioids-2020-purlple-team/00_source/US_VitalStatistics/UnderlyingCauseofDeath2008.txt",
    sep="\t",
    skipfooter=15,
    engine="python",
)
# Drop the Notes column
deaths_2008 = deaths_2008.drop(columns=["Notes"])

deaths_2008

,County,County Code,Year,Year Code,Drug/Alcohol Induced Cause,Drug/Alcohol Induced Cause Code,Deaths
0,"Autauga County, AL",1001,2008.0,2008.0,All other non-drug and non-alcohol causes,O9,448.0
1,"Baldwin County, AL",1003,2008.0,2008.0,Drug poisonings (overdose) Unintentional (X40-...,D1,19.0
2,"Baldwin County, AL",1003,2008.0,2008.0,All other alcohol-induced causes,A9,12.0
3,"Baldwin County, AL",1003,2008.0,2008.0,All other non-drug and non-alcohol causes,O9,1644.0
4,"Barbour County, AL",1005,2008.0,2008.0,All other non-drug and non-alcohol causes,O9,234.0
...,...,...,...,...,...,...,...
4364,"Sweetwater County, WY",56037,2008.0,2008.0,All other non-drug and non-alcohol causes,O9,230.0
4365,"Teton County, WY",56039,2008.0,2008.0,All other non-drug and non-alcohol causes,O9,77.0
4366,"Uinta County, WY",56041,2008.0,2008.0,All other non-drug and non-alcohol causes,O9,131.0
4367,"Washakie County, WY",56043,2008.0,2008.0,All other non-drug and non-alcohol causes,O9,89.0
4368,"Weston County, WY",56045,2008.0,2008.0,All other non-drug and non-alcohol causes,O9,61.0

In [9]:
deaths_2009 = pd.read_csv(
    "/Users/caleboneel/Desktop/estimating-impact-of-opioids-2020-purlple-team/00_source/US_VitalStatistics/UnderlyingCauseofDeath2009.txt",
    sep="\t",
    skipfooter=15,
    engine="python",
)
# Drop the Notes column
deaths_2009 = deaths_2009.drop(columns=["Notes"])

deaths_2009

,County,County Code,Year,Year Code,Drug/Alcohol Induced Cause,Drug/Alcohol Induced Cause Code,Deaths
0,"Autauga County, AL",1001,2009.0,2009.0,All other non-drug and non-alcohol causes,O9,408.0
1,"Baldwin County, AL",1003,2009.0,2009.0,Drug poisonings (overdose) Unintentional (X40-...,D1,29.0
2,"Baldwin County, AL",1003,2009.0,2009.0,All other non-drug and non-alcohol causes,O9,1669.0
3,"Barbour County, AL",1005,2009.0,2009.0,All other non-drug and non-alcohol causes,O9,299.0
4,"Bibb County, AL",1007,2009.0,2009.0,All other non-drug and non-alcohol causes,O9,207.0
...,...,...,...,...,...,...,...
4359,"Sweetwater County, WY",56037,2009.0,2009.0,All other non-drug and non-alcohol causes,O9,241.0
4360,"Teton County, WY",56039,2009.0,2009.0,All other non-drug and non-alcohol causes,O9,69.0
4361,"Uinta County, WY",56041,2009.0,2009.0,All other non-drug and non-alcohol causes,O9,116.0
4362,"Washakie County, WY",56043,2009.0,2009.0,All other non-drug and non-alcohol causes,O9,80.0
4363,"Weston County, WY",56045,2009.0,2009.0,All other non-drug and non-alcohol causes,O9,69.0

In [10]:
deaths_2010 = pd.read_csv(
    "/Users/caleboneel/Desktop/estimating-impact-of-opioids-2020-purlple-team/00_source/US_VitalStatistics/UnderlyingCauseofDeath2010.txt",
    sep="\t",
    skipfooter=15,
    engine="python",
)
# Drop the Notes column
deaths_2010 = deaths_2010.drop(columns=["Notes"])

deaths_2010

,County,County Code,Year,Year Code,Drug/Alcohol Induced Cause,Drug/Alcohol Induced Cause Code,Deaths
0,"Autauga County, AL",1001,2010.0,2010.0,All other non-drug and non-alcohol causes,O9,429.0
1,"Baldwin County, AL",1003,2010.0,2010.0,Drug poisonings (overdose) Unintentional (X40-...,D1,24.0
2,"Baldwin County, AL",1003,2010.0,2010.0,All other alcohol-induced causes,A9,17.0
3,"Baldwin County, AL",1003,2010.0,2010.0,All other non-drug and non-alcohol causes,O9,1754.0
4,"Barbour County, AL",1005,2010.0,2010.0,All other non-drug and non-alcohol causes,O9,281.0
...,...,...,...,...,...,...,...
4436,"Sweetwater County, WY",56037,2010.0,2010.0,All other non-drug and non-alcohol causes,O9,227.0
4437,"Teton County, WY",56039,2010.0,2010.0,All other non-drug and non-alcohol causes,O9,97.0
4438,"Uinta County, WY",56041,2010.0,2010.0,All other non-drug and non-alcohol causes,O9,126.0
4439,"Washakie County, WY",56043,2010.0,2010.0,All other non-drug and non-alcohol causes,O9,85.0
4440,"Weston County, WY",56045,2010.0,2010.0,All other non-drug and non-alcohol causes,O9,69.0

In [11]:
deaths_2011 = pd.read_csv(
    "/Users/caleboneel/Desktop/estimating-impact-of-opioids-2020-purlple-team/00_source/US_VitalStatistics/UnderlyingCauseofDeath2011.txt",
    sep="\t",
    skipfooter=15,
    engine="python",
)
# Drop the Notes column
deaths_2011 = deaths_2011.drop(columns=["Notes"])

deaths_2011

,County,County Code,Year,Year Code,Drug/Alcohol Induced Cause,Drug/Alcohol Induced Cause Code,Deaths
0,"Autauga County, AL",1001,2011.0,2011.0,All other non-drug and non-alcohol causes,O9,447.0
1,"Baldwin County, AL",1003,2011.0,2011.0,Drug poisonings (overdose) Unintentional (X40-...,D1,23.0
2,"Baldwin County, AL",1003,2011.0,2011.0,All other alcohol-induced causes,A9,16.0
3,"Baldwin County, AL",1003,2011.0,2011.0,All other non-drug and non-alcohol causes,O9,1811.0
4,"Barbour County, AL",1005,2011.0,2011.0,All other non-drug and non-alcohol causes,O9,297.0
...,...,...,...,...,...,...,...
4510,"Sweetwater County, WY",56037,2011.0,2011.0,All other non-drug and non-alcohol causes,O9,240.0
4511,"Teton County, WY",56039,2011.0,2011.0,All other non-drug and non-alcohol causes,O9,61.0
4512,"Uinta County, WY",56041,2011.0,2011.0,All other non-drug and non-alcohol causes,O9,126.0
4513,"Washakie County, WY",56043,2011.0,2011.0,All other non-drug and non-alcohol causes,O9,85.0
4514,"Weston County, WY",56045,2011.0,2011.0,All other non-drug and non-alcohol causes,O9,70.0

In [12]:
deaths_2012 = pd.read_csv(
    "/Users/caleboneel/Desktop/estimating-impact-of-opioids-2020-purlple-team/00_source/US_VitalStatistics/UnderlyingCauseofDeath2012.txt",
    sep="\t",
    skipfooter=15,
    engine="python",
)
# Drop the Notes column
deaths_2012 = deaths_2012.drop(columns=["Notes"])

deaths_2012

,County,County Code,Year,Year Code,Drug/Alcohol Induced Cause,Drug/Alcohol Induced Cause Code,Deaths
0,"Autauga County, AL",1001,2012.0,2012.0,All other non-drug and non-alcohol causes,O9,508.0
1,"Baldwin County, AL",1003,2012.0,2012.0,Drug poisonings (overdose) Unintentional (X40-...,D1,24.0
2,"Baldwin County, AL",1003,2012.0,2012.0,All other alcohol-induced causes,A9,20.0
3,"Baldwin County, AL",1003,2012.0,2012.0,All other non-drug and non-alcohol causes,O9,1746.0
4,"Barbour County, AL",1005,2012.0,2012.0,All other non-drug and non-alcohol causes,O9,270.0
...,...,...,...,...,...,...,...
4529,"Sweetwater County, WY",56037,2012.0,2012.0,All other non-drug and non-alcohol causes,O9,280.0
4530,"Teton County, WY",56039,2012.0,2012.0,All other non-drug and non-alcohol causes,O9,81.0
4531,"Uinta County, WY",56041,2012.0,2012.0,All other non-drug and non-alcohol causes,O9,113.0
4532,"Washakie County, WY",56043,2012.0,2012.0,All other non-drug and non-alcohol causes,O9,87.0
4533,"Weston County, WY",56045,2012.0,2012.0,All other non-drug and non-alcohol causes,O9,71.0

In [13]:
deaths_2013 = pd.read_csv(
    "/Users/caleboneel/Desktop/estimating-impact-of-opioids-2020-purlple-team/00_source/US_VitalStatistics/UnderlyingCauseofDeath2013.txt",
    sep="\t",
    skipfooter=15,
    engine="python",
)
# Drop the Notes column
deaths_2013 = deaths_2013.drop(columns=["Notes"])

deaths_2013

,County,County Code,Year,Year Code,Drug/Alcohol Induced Cause,Drug/Alcohol Induced Cause Code,Deaths
0,"Autauga County, AL",1001,2013.0,2013.0,All other non-drug and non-alcohol causes,O9,526.0
1,"Baldwin County, AL",1003,2013.0,2013.0,Drug poisonings (overdose) Unintentional (X40-...,D1,20.0
2,"Baldwin County, AL",1003,2013.0,2013.0,All other alcohol-induced causes,A9,14.0
3,"Baldwin County, AL",1003,2013.0,2013.0,All other non-drug and non-alcohol causes,O9,1934.0
4,"Barbour County, AL",1005,2013.0,2013.0,All other non-drug and non-alcohol causes,O9,273.0
...,...,...,...,...,...,...,...
4589,"Sweetwater County, WY",56037,2013.0,2013.0,All other non-drug and non-alcohol causes,O9,238.0
4590,"Teton County, WY",56039,2013.0,2013.0,All other non-drug and non-alcohol causes,O9,83.0
4591,"Uinta County, WY",56041,2013.0,2013.0,All other non-drug and non-alcohol causes,O9,130.0
4592,"Washakie County, WY",56043,2013.0,2013.0,All other non-drug and non-alcohol causes,O9,72.0
4593,"Weston County, WY",56045,2013.0,2013.0,All other non-drug and non-alcohol causes,O9,66.0

In [14]:
deaths_2014 = pd.read_csv(
    "/Users/caleboneel/Desktop/estimating-impact-of-opioids-2020-purlple-team/00_source/US_VitalStatistics/UnderlyingCauseofDeath2014.txt",
    sep="\t",
    skipfooter=15,
    engine="python",
)
# Drop the Notes column
deaths_2014 = deaths_2014.drop(columns=["Notes"])

deaths_2014

,County,County Code,Year,Year Code,Drug/Alcohol Induced Cause,Drug/Alcohol Induced Cause Code,Deaths
0,"Autauga County, AL",1001,2014.0,2014.0,All other non-drug and non-alcohol causes,O9,475.0
1,"Baldwin County, AL",1003,2014.0,2014.0,Drug poisonings (overdose) Unintentional (X40-...,D1,32.0
2,"Baldwin County, AL",1003,2014.0,2014.0,All other alcohol-induced causes,A9,17.0
3,"Baldwin County, AL",1003,2014.0,2014.0,All other non-drug and non-alcohol causes,O9,1894.0
4,"Barbour County, AL",1005,2014.0,2014.0,All other non-drug and non-alcohol causes,O9,295.0
...,...,...,...,...,...,...,...
4646,"Sweetwater County, WY",56037,2014.0,2014.0,All other non-drug and non-alcohol causes,O9,261.0
4647,"Teton County, WY",56039,2014.0,2014.0,All other non-drug and non-alcohol causes,O9,83.0
4648,"Uinta County, WY",56041,2014.0,2014.0,All other non-drug and non-alcohol causes,O9,136.0
4649,"Washakie County, WY",56043,2014.0,2014.0,All other non-drug and non-alcohol causes,O9,77.0
4650,"Weston County, WY",56045,2014.0,2014.0,All other non-drug and non-alcohol causes,O9,81.0

In [15]:
deaths_2015 = pd.read_csv(
    "/Users/caleboneel/Desktop/estimating-impact-of-opioids-2020-purlple-team/00_source/US_VitalStatistics/UnderlyingCauseofDeath2015.txt",
    sep="\t",
    skipfooter=15,
    engine="python",
)
# Drop the Notes column
deaths_2015 = deaths_2015.drop(columns=["Notes"])

deaths_2015

,County,County Code,Year,Year Code,Drug/Alcohol Induced Cause,Drug/Alcohol Induced Cause Code,Deaths
0,"Autauga County, AL",1001,2015.0,2015.0,All other non-drug and non-alcohol causes,O9,513
1,"Baldwin County, AL",1003,2015.0,2015.0,Drug poisonings (overdose) Unintentional (X40-...,D1,40
2,"Baldwin County, AL",1003,2015.0,2015.0,All other alcohol-induced causes,A9,18
3,"Baldwin County, AL",1003,2015.0,2015.0,All other non-drug and non-alcohol causes,O9,2030
4,"Barbour County, AL",1005,2015.0,2015.0,All other non-drug and non-alcohol causes,O9,293
...,...,...,...,...,...,...,...
4778,"Sweetwater County, WY",56037,2015.0,2015.0,All other non-drug and non-alcohol causes,O9,251
4779,"Teton County, WY",56039,2015.0,2015.0,All other non-drug and non-alcohol causes,O9,95
4780,"Uinta County, WY",56041,2015.0,2015.0,All other non-drug and non-alcohol causes,O9,142
4781,"Washakie County, WY",56043,2015.0,2015.0,All other non-drug and non-alcohol causes,O9,81
4782,"Weston County, WY",56045,2015.0,2015.0,All other non-drug and non-alcohol causes,O9,61

In [16]:
# Initialize a new data frame and stack the individual years  data sets on top of one another

vitality = pd.DataFrame()
vitality.shape[0]

0

In [17]:
# Add asserts to make sure that the number of rows are added correctly and all data is put in the new dataframe

vitality = pd.concat([deaths_2003, deaths_2004], ignore_index = True)
assert vitality.shape[0] == (deaths_2003.shape[0] + deaths_2004.shape[0])

In [18]:
dfrows = vitality.shape[0]

vitality = pd.concat([vitality, deaths_2005], ignore_index = True)

assert vitality.shape[0] == (dfrows + deaths_2005.shape[0])

In [19]:
dfrows = vitality.shape[0]

vitality = pd.concat([vitality, deaths_2006], ignore_index = True)

assert vitality.shape[0] == (dfrows + deaths_2006.shape[0])

In [20]:
dfrows = vitality.shape[0]

vitality = pd.concat([vitality, deaths_2007], ignore_index = True)

assert vitality.shape[0] == (dfrows + deaths_2007.shape[0])

In [21]:
dfrows = vitality.shape[0]

vitality = pd.concat([vitality, deaths_2008], ignore_index = True)

assert vitality.shape[0] == (dfrows + deaths_2008.shape[0])

In [22]:
dfrows = vitality.shape[0]

vitality = pd.concat([vitality, deaths_2009], ignore_index = True)

assert vitality.shape[0] == (dfrows + deaths_2009.shape[0])

In [23]:
dfrows = vitality.shape[0]

vitality = pd.concat([vitality, deaths_2010], ignore_index = True)

assert vitality.shape[0] == (dfrows + deaths_2010.shape[0])

In [24]:
dfrows = vitality.shape[0]

vitality = pd.concat([vitality, deaths_2011], ignore_index = True)

assert vitality.shape[0] == (dfrows + deaths_2011.shape[0])

In [25]:
dfrows = vitality.shape[0]

vitality = pd.concat([vitality, deaths_2012], ignore_index = True)

assert vitality.shape[0] == (dfrows + deaths_2012.shape[0])

In [26]:
dfrows = vitality.shape[0]

vitality = pd.concat([vitality, deaths_2013], ignore_index = True)

assert vitality.shape[0] == (dfrows + deaths_2013.shape[0])

In [27]:
dfrows = vitality.shape[0]

vitality = pd.concat([vitality, deaths_2014], ignore_index = True)

assert vitality.shape[0] == (dfrows + deaths_2014.shape[0])

In [28]:
dfrows = vitality.shape[0]

vitality = pd.concat([vitality, deaths_2015], ignore_index = True)

assert vitality.shape[0] == (dfrows + deaths_2015.shape[0])

In [29]:
vitality

,County,County Code,Year,Year Code,Drug/Alcohol Induced Cause,Drug/Alcohol Induced Cause Code,Deaths
0,"Autauga County, AL",1001,2003.0,2003.0,All other non-drug and non-alcohol causes,O9,397
1,"Baldwin County, AL",1003,2003.0,2003.0,Drug poisonings (overdose) Unintentional (X40-...,D1,10
2,"Baldwin County, AL",1003,2003.0,2003.0,All other alcohol-induced causes,A9,14
3,"Baldwin County, AL",1003,2003.0,2003.0,All other non-drug and non-alcohol causes,O9,1479
4,"Barbour County, AL",1005,2003.0,2003.0,All other non-drug and non-alcohol causes,O9,287
...,...,...,...,...,...,...,...
57236,"Sweetwater County, WY",56037,2015.0,2015.0,All other non-drug and non-alcohol causes,O9,251
57237,"Teton County, WY",56039,2015.0,2015.0,All other non-drug and non-alcohol causes,O9,95
57238,"Uinta County, WY",56041,2015.0,2015.0,All other non-drug and non-alcohol causes,O9,142
57239,"Washakie County, WY",56043,2015.0,2015.0,All other non-drug and non-alcohol causes,O9,81
57240,"Weston County, WY",56045,2015.0,2015.0,All other non-drug and non-alcohol causes,O9,61

In [30]:
# Check that there is a reasonable number of rows for each year
vitality['Year'].value_counts()

2015.0    4783
2014.0    4651
2013.0    4594
2012.0    4534
2011.0    4515
2010.0    4441
2008.0    4369
2009.0    4364
2007.0    4304
2006.0    4262
2005.0    4202
2004.0    4135
2003.0    4087
Name: Year, dtype: int64

In [31]:
# Dropping all observations that do not have a cause of death related to drug overdose

drugCodes = ['D1', 'D2', 'D4', 'D9']
drug_vitality1 = vitality[vitality['Drug/Alcohol Induced Cause Code'].isin(drugCodes)]

drug_vitality1['Drug/Alcohol Induced Cause Code'].value_counts()

D1    7573
D2    1465
D4     761
D9     628
Name: Drug/Alcohol Induced Cause Code, dtype: int64

In [32]:
# Rename columns to make them less cumbersome
drug_vitality2 = drug_vitality1.copy()
drug_vitality2.rename(columns = {'Drug/Alcohol Induced Cause Code':'Death Code', 'Drug/Alcohol Induced Cause':'Cause of Death'}, inplace = True)

In [33]:
drug_vitality = drug_vitality2.copy()

In [34]:
#Drog extraneous column "Year Code" which is the same as year, also drop the last line of data in the framew which is a wierd na/year value that was accidently added

drug_vitality.drop(['Year Code'], axis=1, inplace = True)
drug_vitality.drop(drug_vitality.tail(1).index,inplace=True)

In [35]:
# Check the Data frame for Null values 

drug_vitality['County'].isnull().values.any()
drug_vitality['County Code'].isnull().values.any()
drug_vitality['Year'].isnull().values.any()
drug_vitality['Cause of Death'].isnull().values.any()
drug_vitality['Death Code'].isnull().values.any()
drug_vitality['Deaths'].isnull().values.any()

False

In [36]:
drug_vitality[drug_vitality['County']=='Acadia Parish, LA']

,County,County Code,Year,Cause of Death,Death Code,Deaths
1459,"Acadia Parish, LA",22001,2003.0,Drug poisonings (overdose) Unintentional (X40-...,D1,11
9735,"Acadia Parish, LA",22001,2005.0,Drug poisonings (overdose) Unintentional (X40-...,D1,23
13951,"Acadia Parish, LA",22001,2006.0,Drug poisonings (overdose) Unintentional (X40-...,D1,19
18228,"Acadia Parish, LA",22001,2007.0,Drug poisonings (overdose) Undetermined (Y10-Y14),D4,19
26945,"Acadia Parish, LA",22001,2009.0,Drug poisonings (overdose) Undetermined (Y10-Y14),D4,11
31320,"Acadia Parish, LA",22001,2010.0,Drug poisonings (overdose) Undetermined (Y10-Y14),D4,13
35769,"Acadia Parish, LA",22001,2011.0,Drug poisonings (overdose) Undetermined (Y10-Y14),D4,10

In [37]:
# Create a copy of the final data set to create version with total deaths per county per year, not taking type of overdose into account

od_deaths = drug_vitality.copy()

In [38]:
#Drop drug cause of death and code

od_deaths.drop(['Cause of Death', 'Death Code'], axis = 1, inplace = True)

In [39]:
#Groupby County and Year 

od_deaths = od_deaths.groupby(["County", "County Code", "Year"], as_index = False).sum()

In [40]:
# Final Dataset

od_deaths

                 County  County Code    Year Deaths
0     Acadia Parish, LA        22001  2003.0     11
1     Acadia Parish, LA        22001  2005.0     23
2     Acadia Parish, LA        22001  2006.0     19
3     Acadia Parish, LA        22001  2007.0     19
4     Acadia Parish, LA        22001  2009.0     11
...                 ...          ...     ...    ...
7919    Yuma County, AZ         4027  2011.0     20
7920    Yuma County, AZ         4027  2012.0     32
7921    Yuma County, AZ         4027  2013.0     22
7922    Yuma County, AZ         4027  2014.0     35
7923    Yuma County, AZ         4027  2015.0     24

[7924 rows x 4 columns]